### ISSUE TITLE
QC reports for key processing steps

### ISSUE THREAD

**Issue by gagnonanthony** [scilus/nf-pediatric#7]
### Description of feature

To ensure processing quality and to integrate with multiqc report, it would be beneficial to include QC images in a single-subject MultiQC report:

- [x] Tissue segmentation (#6)
- [x] Labels (#6)
- [x] Shells (#6)
- [x] Metrics (#6)
- [x] Tracking coverage (#6)
- [x] Registration process. (#24) 
- [x] Eddy/Topup (#24) 

And quantitative assessment on a population level:

- [x] Dice score between TDI mask and tracking mask. (#6)
- [x] Streamline count in whole-brain tractogram. (#6)
- [x] Volume, area, thickness of cortical and subcortical regions. (#6)

For each section, add:

- [ ] Describe what the images or plots mean and how to evaluate their quality. 
- [x] Ensure data within the plot are easily exportable in CSV format with the associated subject's ID. (#6)
